### ISSUE TITLE
Hosting monorepo, react native

### ISSUE THREAD

**Issue by Kerim-Willem** [trpc/zart#27]
Hi there, 

First of all great job with this whole setup. Looking forward to work with it a lot! There's something I don't understand though, and I hope I'm at the right place to ask this question. 

But how do you actually host this monorepo? This is mainly confusing to me because of the React Native part. Isn't it so that your React Native code gets bundled in it's entirety and gets uploaded to the App Store/Google Play Store? If so, wouldn't that mean that we have to upload the entire nextjs and trpc as well? Which would make the app slower than it needs to be? 

I'm trying to look for resources online to give me a better understanding, but I can't find it. I would appreciate if you can point me into the right direction. 

Keep up the good work!

**Comment by KATT** [comment]
The next app and it's API which the RN app is using is hosted on vercel

**Comment by Kerim-Willem** [comment]
Sorry for the confusion but what I meant is; If I push my React Native code to the App store, do I also have to push the trpc backend code as well?

**Comment by KATT** [comment]
Please ask your questions on http://trpc.io/discord or on https://github.com/trpc/trpc/discussions 🙏
